ALTER TABLE weather_snapshot
    ADD COLUMN location_name VARCHAR(160),
    ADD COLUMN region_name VARCHAR(160),
    ADD COLUMN country_name VARCHAR(160),
    ADD COLUMN timezone_id VARCHAR(120),
    ADD COLUMN localtime_epoch BIGINT,
    ADD COLUMN location_localtime VARCHAR(64),
    ADD COLUMN last_updated_epoch BIGINT,
    ADD COLUMN last_updated VARCHAR(64),
    ADD COLUMN temperature_f DOUBLE PRECISION,
    ADD COLUMN is_day INT,
    ADD COLUMN condition_code INT,
    ADD COLUMN wind_mph DOUBLE PRECISION,
    ADD COLUMN wind_degree INT,
    ADD COLUMN wind_dir VARCHAR(32),
    ADD COLUMN pressure_mb DOUBLE PRECISION,
    ADD COLUMN pressure_in DOUBLE PRECISION,
    ADD COLUMN precip_in DOUBLE PRECISION,
    ADD COLUMN cloud INT,
    ADD COLUMN feels_like_f DOUBLE PRECISION,
    ADD COLUMN windchill_c DOUBLE PRECISION,
    ADD COLUMN windchill_f DOUBLE PRECISION,
    ADD COLUMN heatindex_c DOUBLE PRECISION,
    ADD COLUMN heatindex_f DOUBLE PRECISION,
    ADD COLUMN dewpoint_c DOUBLE PRECISION,
    ADD COLUMN dewpoint_f DOUBLE PRECISION,
    ADD COLUMN vis_km DOUBLE PRECISION,
    ADD COLUMN vis_miles DOUBLE PRECISION,
    ADD COLUMN uv DOUBLE PRECISION,
    ADD COLUMN gust_mph DOUBLE PRECISION,
    ADD COLUMN gust_kph DOUBLE PRECISION,
    ADD COLUMN air_quality_co DOUBLE PRECISION,
    ADD COLUMN air_quality_no2 DOUBLE PRECISION,
    ADD COLUMN air_quality_o3 DOUBLE PRECISION,
    ADD COLUMN air_quality_so2 DOUBLE PRECISION,
    ADD COLUMN air_quality_pm2_5 DOUBLE PRECISION,
    ADD COLUMN air_quality_pm10 DOUBLE PRECISION,
    ADD COLUMN air_quality_us_epa_index INT,
    ADD COLUMN air_quality_gb_defra_index INT;
