news.api.cleanupCron=${NEWS_API_CLEANUP_CRON}
news.api.quotaResetCron=${NEWS_API_QUOTA_RESET_CRON}
news.api.schedulerCron=${NEWS_API_SCHEDULER_CRON}
market.api.ingestion-cron=${MARKET_API_INGESTION_CRON}
weather.scheduler-cron=${WEATHER_SCHEDULER_CRON}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
otp.cleanup-cron=${OTP_CLEANUP_CRON}
crop.cleanup-cron=${CROP_CLEANUP_CRON}
news.api.ingest-on-startup=${NEWS_API_INGEST_ON_STARTUP}
spring.datasource.url=jdbc:mysql://aagriggate-db.cfymmesucvbo.eu-north-1.rds.amazonaws.com:3306/aagriggate?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=admin
spring.datasource.password=Vighnesh1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true