news.api.cleanupCron=${NEWS_API_CLEANUP_CRON}
news.api.quotaResetCron=${NEWS_API_QUOTA_RESET_CRON}
news.api.schedulerCron=${NEWS_API_SCHEDULER_CRON}
market.api.ingestion-cron=${MARKET_API_INGESTION_CRON}
weather.scheduler-cron=${WEATHER_SCHEDULER_CRON}
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
otp.cleanup-cron=${OTP_CLEANUP_CRON}
crop.cleanup-cron=${CROP_CLEANUP_CRON}
news.api.ingest-on-startup=${NEWS_API_INGEST_ON_STARTUP}