spring:
  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

jwt:
  secret: ${JWT_SECRET}

weather:
  api:
    url: ${WEATHER_API_URL}
    key: ${WEATHER_API_KEY}

market:
  api:
    url: ${MARKET_API_URL}
    key: ${MARKET_API_KEY}

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
