spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/app}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  security:
    user:
      name: ${APP_SECURITY_USER:vighnesh}
      password: ${APP_SECURITY_PASSWORD:v123}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${EMAIL_USERNAME:webappfarmer@gmail.com}
    password: ${EMAIL_PASSWORD:syoz atph yahs vfts}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  # your project currently generates dynamic secret,
  # but this is proper fixed fallback
  secret: ${JWT_SECRET:YWFncmlnZ2F0ZS1zZWN1cmUtand0LXNlY3JldC1rZXktMjAyNi1mZWItMjM=}

weather:
  api:
    url: ${WEATHER_API_URL:https://api.weatherapi.com/v1/current.json}
    key: ${WEATHER_API_KEY:75f97057caa641fa99c73509242910}

market:
  api:
    url: ${MARKET_API_URL:https://api.data.gov.in/resource/35985678-0d79-46b4-9ed6-6f13308a1d24}
    key: ${MARKET_API_KEY:579b464db66ec23bdd000001602edb9ef1a64cd961329419d730f705}   # your project currently does not use API key

location:
  api:
    url: ${MARKET_API_URL:https://api.opencagedata.com/geocode/v1/json}
    key: ${MARKET_API_KEY:4138beff07ea4a259f0c2ff71ba19378}
#  const res = await fetch(
#    `https://api.opencagedata.com/geocode/v1/json?q=${coords.latitude}+${coords.longitude}&key=4138beff07ea4a259f0c2ff71ba19378`
#    );
admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin123}
#